# Generated by Django 4.0.2 on 2022-02-19 12:22

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_5', '0003_alter_bouquet_id_alter_client_id_alter_flower_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bouquet',
            managers=[
                ('shop', django.db.models.manager.Manager()),
            ],
        ),
    ]
